version: '3.9'

services:
#     app:
#         container_name: snippetbox_app
#         tty: true
#         build:
#             context: .
#             dockerfile: _docker/local/app/Dockerfile
#         ports:
#             - 4000:4000
#         restart: on-failure
#         depends_on:
#             - db
#         links:
#             - db

     db:
        image: mysql:latest
        container_name: mysql_db
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: mypassword
        volumes:
            - ./tmp/mysql_db:/var/lib/mysql
            - ./storage/migration.sql:/docker-entrypoint-initdb.d/1.sql
        ports:
            - 3306:3306
